package com.core.ads.admob

object TestNativeAdHeadlineUtils {
    private val blockedHeadlines = setOf(
        "Test Ad",
        "Toetsadvertensie",
        "የሙከራ ማስታወቂያ",
        "إعلان تجريبي",
        "পৰীক্ষণ বিজ্ঞাপন",
        "Test Reklamı",
        "Probni oglas",
        "Тэставая рэклама",
        "Тестова реклама",
        "পরীক্ষামূলক বিজ্ঞাপন",
        "Anunci de prova",
        "Zkušební reklama",
        "Testannonce",
        "Testanzeige",
        "Δοκιμαστική διαφήμιση",
        "Anuncio de prueba",
        "Testreklaam",
        "Probako iragarkia",
        "آگهی آزمایشی",
        "Testimainos",
        "Annonce test",
        "Probar anuncio",
        "પરીક્ષણની જાહેરાત",
        "जाँच विज्ञापन",
        "Testni oglas",
        "Teszthirdetés",
        "Փորձարկել գովազդը",
        "Tes Iklan",
        "Prófa auglýsingu",
        "Annuncio di testo",
        "מודעת בדיקה",
        "テスト広告",
        "სატესტო რეკლამა",
        "Сынақ жарнама",
        "ពាណិជ្ជកម្ម​សាកល្បង",
        "ಪರೀಕ್ಷಾ ಜಾಹೀರಾತು",
        "테스트 광고",
        "Жарнаманы сынап көрүңүз",
        "ໂຄສະນາທົດສອບ",
        "Bandomasis skelbimas",
        "Testa reklāma",
        "Тестирај ја рекламата",
        "പരസ്യം പരീക്ഷിക്കുക",
        "Тест зар",
        "चाचणी जाहिरात",
        "Iklan Ujian",
        "စမ်းသပ်ကြော်ငြာ",
        "Testannonse",
        "परीक्षण विज्ञापन",
        "Testadvertentie",
        "ପରୀକ୍ଷାମୂଳକ ବିଜ୍ଞାପନ",
        "ਟੈਸਟ ਇਸ਼ਤਿਹਾਰ",
        "Reklama testowa",
        "Anúncio de teste",
        "Anunț de probă",
        "Тестовое объявление",
        "පරීක්ෂණ වෙළඳ දැන්වීම",
        "Testovacia reklama",
        "Preizkusni oglas",
        "Reklamë test",
        "Пробни оглас",
        "Testannons",
        "Tangazo la Jaribio",
        "சோதனை விளம்பரம்",
        "ప్రకటనను పరీక్షించండి",
        "โฆษณาทดสอบ",
        "Pansubok na Ad",
        "Тестове оголошення",
        "اشتہار ٹیسٹ کریں",
        "Test reklama",
        "Quảng cáo thử nghiệm",
        "测试广告",
        "測試廣告",
        "Hlola isikhangiso"
    )

    fun containsBlockedHeadline(headline: String?): Boolean {
        val value = headline?.trim().orEmpty()
        if (value.isEmpty()) return false
        return blockedHeadlines.any { blockedHeadline ->
            value.contains(blockedHeadline, ignoreCase = true)
        }
    }
}
